[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', 'safe-contracts/=lib/safe-contracts/contracts']
verbosity = 3
sender = '0xed53fa304E7fcbab4E8aCB184F5FC6F69Ed54fF6'
tx_origin = '0xed53fa304E7fcbab4E8aCB184F5FC6F69Ed54fF6'
# See more config options https://github.com/gakonst/foundry/tree/master/config